# ABOUTME: Debug version of Woodpecker CI Pipeline to troubleshoot authentication
# ABOUTME: Tests registry login and provides diagnostic information

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true
      lfs: false

when:
  event: [push, tag, cron, manual]

steps:
  # Step 1: Test secret availability
  test-secrets:
    image: alpine:latest
    commands:
      - echo "Testing secret availability..."
      - echo "nexus_username exists:" $(if [ -n "$nexus_username" ]; then echo "YES"; else echo "NO"; fi)
      - echo "nexus_username length:" $(echo -n "$nexus_username" | wc -c)
      - echo "nexus_password exists:" $(if [ -n "$nexus_password" ]; then echo "YES"; else echo "NO"; fi)
      - echo "nexus_password length:" $(echo -n "$nexus_password" | wc -c)
    secrets: [nexus_username, nexus_password]
    when:
      event: [push, manual]

  # Step 2: Test Docker login manually
  test-docker-login:
    image: docker:latest
    commands:
      - echo "Testing Docker login to registry..."
      - echo "Attempting login with nexus_username..."
      - echo "$nexus_password" | docker login docker-push.acn.fr -u "$nexus_username" --password-stdin && echo "✓ Login successful!" || echo "✗ Login failed"
    secrets: [nexus_username, nexus_password]
    when:
      event: [push, manual]

  # Step 3: Simple build without push to test plugin authentication
  build-test-plugin:
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      dry_run: true  # Don't actually push
      registry: docker-push.acn.fr
      repo: docker-push.acn.fr/openspp/openspp
      dockerfile: Dockerfile
      platforms: linux/amd64
      tags:
        - test-${CI_COMMIT_SHA:0:8}
      username:
        from_secret: nexus_username
      password:
        from_secret: nexus_password
    when:
      event: [push, manual]

  # Step 4: Alternative authentication method using explicit Docker commands
  build-with-explicit-login:
    image: docker:latest
    privileged: true
    commands:
      - echo "Setting up Docker buildx..."
      - docker buildx create --use --name mybuilder || true
      - docker buildx inspect --bootstrap
      - echo "Logging in to registry with nexus_username..."
      - echo "$nexus_password" | docker login docker-push.acn.fr -u "$nexus_username" --password-stdin
      - echo "Building image..."
      - docker buildx build --platform linux/amd64 -t docker-push.acn.fr/openspp/openspp:test-manual-${CI_COMMIT_SHA:0:8} -f Dockerfile .
      - echo "Build completed (dry run - not pushing)"
    secrets: [nexus_username, nexus_password]
    when:
      event: [push, manual]